# Generated by Django 4.2.1 on 2024-01-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
